version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fast-app-prod
    working_dir: /app
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .envs/.prod.env
    environment:
      - ENV=prod
      - PYTHONPATH=/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-prod
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/prod.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
