FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install --upgrade pip \
    && pip install "poetry==2.1.1" \
    && poetry config virtualenvs.create false \
    && poetry install --no-root

COPY . .

CMD ["/bin/bash", "-c", "test -f .aerich.ini && aerich upgrade || echo 'No aerich config, skipping upgrade'; gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --uvicorn-args '--proxy-headers'"]
