version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fast-app-dev
    working_dir: /app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .envs/.dev.env
    environment:
      - ENV=dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_DB: "senior"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1q2w3e4r"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
