
services:
  backend-fast:
    image: hak2881/senior:latest
    container_name: fast-app-prod
    working_dir: /app
    restart: always
    expose:
      - :"8000"
    env_file:
      - .envs/.prod.env
    environment:
      - ENV=prod
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - front
      - back

  redis:
    image: redis:alpine
    container_name: redis-prod
    restart: always
    expose:
      - "6379"
    networks:
      - back

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/prod.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend-fast
    networks:
      - front
