networks:
  front:
    driver: bridge
  back:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/dev.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend-fast
    networks:
      - front

  backend-fast:
    image: hak2881/senior:latest
    container_name: fast-app-prod
    working_dir: /app
    restart: always
    expose:
      - "8000"
    env_file:
      - .envs/.prod.env
    environment:
      - ENV=prod
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - front
      - back

  redis:
    image: redis:alpine
    container_name: redis-prod
    restart: always
    expose:
      - "6379"
    networks:
      - back

  frontend-next:
    image: next-app-dev:latest
    # 플랫폼 지정 (이걸로 빌드하면 맥북에선 안돌아갈듯 / 리눅스 용)
    platform: linux/amd64

    # 환경 변수 추가해주기 (직접 넣거나, .env 변수로 받아서 넣거나)
    env_file:
      - ../.env
    # environment:
    #   - NAVER_MAP_KEY=${NAVER_MAP_KEY}
    #   - ENV1=example1

    expose:
      - "3000"

    # 이 옵션이 있으면 재시작을 위해서 pm2가 필요없는게 확실한지 더블체크!
    restart: unless-stopped
    networks:
      - front
