FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install --upgrade pip \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root

COPY . .

CMD ["/bin/bash", "-c", "test -f .aerich.ini && aerich upgrade || echo 'No aerich config, skipping upgrade'; uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
