name: Full Code Checks

on:
  push:
    branches: "*"
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1q2w3e4r
          POSTGRES_DB: senior
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Run Black
        run: poetry run black . --check

      - name: Run Isort
        run: poetry run isort . --check-only

      - name: Run Tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1q2w3e4r
          POSTGRES_DB: senior
        run: |
          poetry run pytest || echo "No tests found, skipping failure."
