name: Deploy to EC2 with Docker
on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.dev
#          file: Dockerfile.prod # 배포
          push: true
          tags: hak2881/senior:latest
          no-cache: true

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            sudo docker pull hak2881/senior:latest
            sudo docker compose -f docker-compose.dev.yml down
            sudo docker compose -f docker-compose.dev.yml up -d
#            sudo docker compose -f docker-compose.prod.yml down
#            sudo docker compose -f docker-compose.prod.yml up -d
            sudo docker system prune -f
